// Icon is generated by scripts/generate_icon.ps1 (PowerShell + GDI+).
// This file is kept as a placeholder so the test directory structure is clear.
// To regenerate: run scripts/generate_icon.ps1 from the repo root,
// then run: dart run flutter_launcher_icons
