// Icon is generated by scripts/generate_icon.ps1 (PowerShell + GDI+).
// To regenerate: run scripts/generate_icon.ps1 from the repo root,
// then run: dart run flutter_launcher_icons

void main() {}
