// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/fan_device.dart';
import 'models/fan_state.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7689092753891102258),
    name: 'FanDevice',
    lastPropertyId: const obx_int.IdUid(8, 8724215114432112353),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 147237961700563683),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5823485703107898771),
        name: 'deviceId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 5348191743963573787),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3331529959578822022),
        name: 'macAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3190024517310603103),
        name: 'model',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2480271103966888844),
        name: 'nickname',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2392897008800705772),
        name: 'fwVersion',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3502758498536394249),
        name: 'addedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8724215114432112353),
        name: 'lastConnectedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6584660752010918141),
    name: 'FanState',
    lastPropertyId: const obx_int.IdUid(9, 8865044660608720712),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2292579713487665491),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2791726193527070308),
        name: 'deviceId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 2741298653888021969),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8142245391772955900),
        name: 'speed',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5354836785458515567),
        name: 'isBoost',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6223183583105743213),
        name: 'activeMode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9012323104763062137),
        name: 'activeTimerCode',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1944379048785015591),
        name: 'isPowered',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2621239356923991583),
        name: 'lastWatts',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8865044660608720712),
        name: 'lastRpm',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 6584660752010918141),
    lastIndexId: const obx_int.IdUid(2, 2741298653888021969),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FanDevice: obx_int.EntityDefinition<FanDevice>(
      model: _entities[0],
      toOneRelations: (FanDevice object) => [],
      toManyRelations: (FanDevice object) => {},
      getId: (FanDevice object) => object.id,
      setId: (FanDevice object, int id) {
        object.id = id;
      },
      objectToFB: (FanDevice object, fb.Builder fbb) {
        final deviceIdOffset = fbb.writeString(object.deviceId);
        final macAddressOffset = fbb.writeString(object.macAddress);
        final modelOffset = fbb.writeString(object.model);
        final nicknameOffset = fbb.writeString(object.nickname);
        final fwVersionOffset = fbb.writeString(object.fwVersion);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, deviceIdOffset);
        fbb.addOffset(2, macAddressOffset);
        fbb.addOffset(3, modelOffset);
        fbb.addOffset(4, nicknameOffset);
        fbb.addOffset(5, fwVersionOffset);
        fbb.addInt64(6, object.addedAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.lastConnectedAt?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastConnectedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final object = FanDevice()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..deviceId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..macAddress = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..model = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..nickname = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..fwVersion = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..addedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
          )
          ..lastConnectedAt = lastConnectedAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(lastConnectedAtValue);

        return object;
      },
    ),
    FanState: obx_int.EntityDefinition<FanState>(
      model: _entities[1],
      toOneRelations: (FanState object) => [],
      toManyRelations: (FanState object) => {},
      getId: (FanState object) => object.id,
      setId: (FanState object, int id) {
        object.id = id;
      },
      objectToFB: (FanState object, fb.Builder fbb) {
        final deviceIdOffset = fbb.writeString(object.deviceId);
        final activeModeOffset = object.activeMode == null
            ? null
            : fbb.writeString(object.activeMode!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, deviceIdOffset);
        fbb.addInt64(2, object.speed);
        fbb.addBool(3, object.isBoost);
        fbb.addOffset(4, activeModeOffset);
        fbb.addInt64(5, object.activeTimerCode);
        fbb.addBool(6, object.isPowered);
        fbb.addInt64(7, object.lastWatts);
        fbb.addInt64(8, object.lastRpm);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = FanState()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..deviceId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..speed = const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
          ..isBoost = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            10,
            false,
          )
          ..activeMode = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 12)
          ..activeTimerCode = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            14,
          )
          ..isPowered = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            16,
            false,
          )
          ..lastWatts = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            18,
          )
          ..lastRpm = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            20,
          );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FanDevice] entity fields to define ObjectBox queries.
class FanDevice_ {
  /// See [FanDevice.id].
  static final id = obx.QueryIntegerProperty<FanDevice>(
    _entities[0].properties[0],
  );

  /// See [FanDevice.deviceId].
  static final deviceId = obx.QueryStringProperty<FanDevice>(
    _entities[0].properties[1],
  );

  /// See [FanDevice.macAddress].
  static final macAddress = obx.QueryStringProperty<FanDevice>(
    _entities[0].properties[2],
  );

  /// See [FanDevice.model].
  static final model = obx.QueryStringProperty<FanDevice>(
    _entities[0].properties[3],
  );

  /// See [FanDevice.nickname].
  static final nickname = obx.QueryStringProperty<FanDevice>(
    _entities[0].properties[4],
  );

  /// See [FanDevice.fwVersion].
  static final fwVersion = obx.QueryStringProperty<FanDevice>(
    _entities[0].properties[5],
  );

  /// See [FanDevice.addedAt].
  static final addedAt = obx.QueryDateProperty<FanDevice>(
    _entities[0].properties[6],
  );

  /// See [FanDevice.lastConnectedAt].
  static final lastConnectedAt = obx.QueryDateProperty<FanDevice>(
    _entities[0].properties[7],
  );
}

/// [FanState] entity fields to define ObjectBox queries.
class FanState_ {
  /// See [FanState.id].
  static final id = obx.QueryIntegerProperty<FanState>(
    _entities[1].properties[0],
  );

  /// See [FanState.deviceId].
  static final deviceId = obx.QueryStringProperty<FanState>(
    _entities[1].properties[1],
  );

  /// See [FanState.speed].
  static final speed = obx.QueryIntegerProperty<FanState>(
    _entities[1].properties[2],
  );

  /// See [FanState.isBoost].
  static final isBoost = obx.QueryBooleanProperty<FanState>(
    _entities[1].properties[3],
  );

  /// See [FanState.activeMode].
  static final activeMode = obx.QueryStringProperty<FanState>(
    _entities[1].properties[4],
  );

  /// See [FanState.activeTimerCode].
  static final activeTimerCode = obx.QueryIntegerProperty<FanState>(
    _entities[1].properties[5],
  );

  /// See [FanState.isPowered].
  static final isPowered = obx.QueryBooleanProperty<FanState>(
    _entities[1].properties[6],
  );

  /// See [FanState.lastWatts].
  static final lastWatts = obx.QueryIntegerProperty<FanState>(
    _entities[1].properties[7],
  );

  /// See [FanState.lastRpm].
  static final lastRpm = obx.QueryIntegerProperty<FanState>(
    _entities[1].properties[8],
  );
}
