// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/fan_device.dart';
import 'models/fan_state.dart';
import 'models/usage_log.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7689092753891102258),
    name: 'FanDevice',
    lastPropertyId: const obx_int.IdUid(10, 5638614726256919996),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 147237961700563683),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5823485703107898771),
        name: 'deviceId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 5348191743963573787),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3331529959578822022),
        name: 'macAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3190024517310603103),
        name: 'model',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2480271103966888844),
        name: 'nickname',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2392897008800705772),
        name: 'fwVersion',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3502758498536394249),
        name: 'addedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8724215114432112353),
        name: 'lastConnectedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3742940356637995512),
        name: 'isServiceAccess',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5638614726256919996),
        name: 'serviceExpiresAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6584660752010918141),
    name: 'FanState',
    lastPropertyId: const obx_int.IdUid(22, 1685620198763572186),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2292579713487665491),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2791726193527070308),
        name: 'deviceId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 2741298653888021969),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8142245391772955900),
        name: 'speed',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5354836785458515567),
        name: 'isBoost',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6223183583105743213),
        name: 'activeMode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9012323104763062137),
        name: 'activeTimerCode',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1944379048785015591),
        name: 'isPowered',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2621239356923991583),
        name: 'lastWatts',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8865044660608720712),
        name: 'lastRpm',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7229972512943856743),
        name: 'lastLightColorType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2528041221205574876),
        name: 'lastLightBrightness',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1825458419538538317),
        name: 'lastLightIsOn',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3257475452761487086),
        name: 'openSegmentStart',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 2922610925722302106),
        name: 'openSegmentGear',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 356690034951243647),
        name: 'openSegmentMode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 1968679545250408128),
        name: 'openSegmentSmartBaseline',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 4999734423800603426),
        name: 'openSegmentWattsSum',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 1576495503626155822),
        name: 'openSegmentWattsCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 6520789390621056405),
        name: 'openSegmentRpmSum',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 1038581388731706913),
        name: 'openSegmentRpmCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 5274440309588345344),
        name: 'lastRuntimeSecs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 1685620198763572186),
        name: 'timerActivatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 7745722999259312107),
    name: 'UsageLog',
    lastPropertyId: const obx_int.IdUid(9, 7541423025244100045),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 862387326030390053),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2648413089901042935),
        name: 'deviceId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4021657117346482254),
        name: 'startTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4059261527488277558),
        name: 'durationSecs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8798316521547455166),
        name: 'gear',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2921317936671011541),
        name: 'watts',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1714395182981438629),
        name: 'mode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4350952620612556560),
        name: 'rpm',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7541423025244100045),
        name: 'smartBaselineGear',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 7745722999259312107),
    lastIndexId: const obx_int.IdUid(2, 2741298653888021969),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FanDevice: obx_int.EntityDefinition<FanDevice>(
      model: _entities[0],
      toOneRelations: (FanDevice object) => [],
      toManyRelations: (FanDevice object) => {},
      getId: (FanDevice object) => object.id,
      setId: (FanDevice object, int id) {
        object.id = id;
      },
      objectToFB: (FanDevice object, fb.Builder fbb) {
        final deviceIdOffset = fbb.writeString(object.deviceId);
        final macAddressOffset = fbb.writeString(object.macAddress);
        final modelOffset = fbb.writeString(object.model);
        final nicknameOffset = fbb.writeString(object.nickname);
        final fwVersionOffset = fbb.writeString(object.fwVersion);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, deviceIdOffset);
        fbb.addOffset(2, macAddressOffset);
        fbb.addOffset(3, modelOffset);
        fbb.addOffset(4, nicknameOffset);
        fbb.addOffset(5, fwVersionOffset);
        fbb.addInt64(6, object.addedAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.lastConnectedAt?.millisecondsSinceEpoch);
        fbb.addBool(8, object.isServiceAccess);
        fbb.addInt64(9, object.serviceExpiresAt?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastConnectedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final serviceExpiresAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final object = FanDevice()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..deviceId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..macAddress = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..model = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..nickname = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..fwVersion = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..addedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
          )
          ..lastConnectedAt = lastConnectedAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(lastConnectedAtValue)
          ..isServiceAccess = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            20,
            false,
          )
          ..serviceExpiresAt = serviceExpiresAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(serviceExpiresAtValue);

        return object;
      },
    ),
    FanState: obx_int.EntityDefinition<FanState>(
      model: _entities[1],
      toOneRelations: (FanState object) => [],
      toManyRelations: (FanState object) => {},
      getId: (FanState object) => object.id,
      setId: (FanState object, int id) {
        object.id = id;
      },
      objectToFB: (FanState object, fb.Builder fbb) {
        final deviceIdOffset = fbb.writeString(object.deviceId);
        final activeModeOffset = object.activeMode == null
            ? null
            : fbb.writeString(object.activeMode!);
        final lastLightColorTypeOffset = fbb.writeString(
          object.lastLightColorType,
        );
        final openSegmentModeOffset = object.openSegmentMode == null
            ? null
            : fbb.writeString(object.openSegmentMode!);
        fbb.startTable(23);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, deviceIdOffset);
        fbb.addInt64(2, object.speed);
        fbb.addBool(3, object.isBoost);
        fbb.addOffset(4, activeModeOffset);
        fbb.addInt64(5, object.activeTimerCode);
        fbb.addBool(6, object.isPowered);
        fbb.addInt64(7, object.lastWatts);
        fbb.addInt64(8, object.lastRpm);
        fbb.addOffset(9, lastLightColorTypeOffset);
        fbb.addFloat64(10, object.lastLightBrightness);
        fbb.addBool(11, object.lastLightIsOn);
        fbb.addInt64(12, object.openSegmentStart.millisecondsSinceEpoch);
        fbb.addInt64(13, object.openSegmentGear);
        fbb.addOffset(14, openSegmentModeOffset);
        fbb.addInt64(15, object.openSegmentSmartBaseline);
        fbb.addInt64(16, object.openSegmentWattsSum);
        fbb.addInt64(17, object.openSegmentWattsCount);
        fbb.addInt64(18, object.openSegmentRpmSum);
        fbb.addInt64(19, object.openSegmentRpmCount);
        fbb.addInt64(20, object.lastRuntimeSecs);
        fbb.addInt64(21, object.timerActivatedAt?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final timerActivatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          46,
        );
        final object = FanState()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..deviceId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..speed = const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
          ..isBoost = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            10,
            false,
          )
          ..activeMode = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 12)
          ..activeTimerCode = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            14,
          )
          ..isPowered = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            16,
            false,
          )
          ..lastWatts = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            18,
          )
          ..lastRpm = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            20,
          )
          ..lastLightColorType = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 22, '')
          ..lastLightBrightness = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            24,
            0,
          )
          ..lastLightIsOn = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            26,
            false,
          )
          ..openSegmentStart = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0),
          )
          ..openSegmentGear = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            30,
            0,
          )
          ..openSegmentMode = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 32)
          ..openSegmentSmartBaseline = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            34,
          )
          ..openSegmentWattsSum = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            36,
            0,
          )
          ..openSegmentWattsCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            38,
            0,
          )
          ..openSegmentRpmSum = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            40,
            0,
          )
          ..openSegmentRpmCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            42,
            0,
          )
          ..lastRuntimeSecs = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            44,
          )
          ..timerActivatedAt = timerActivatedAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(timerActivatedAtValue);

        return object;
      },
    ),
    UsageLog: obx_int.EntityDefinition<UsageLog>(
      model: _entities[2],
      toOneRelations: (UsageLog object) => [],
      toManyRelations: (UsageLog object) => {},
      getId: (UsageLog object) => object.id,
      setId: (UsageLog object, int id) {
        object.id = id;
      },
      objectToFB: (UsageLog object, fb.Builder fbb) {
        final deviceIdOffset = fbb.writeString(object.deviceId);
        final modeOffset = object.mode == null
            ? null
            : fbb.writeString(object.mode!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, deviceIdOffset);
        fbb.addInt64(2, object.startTime.millisecondsSinceEpoch);
        fbb.addInt64(3, object.durationSecs);
        fbb.addInt64(4, object.gear);
        fbb.addInt64(5, object.watts);
        fbb.addOffset(6, modeOffset);
        fbb.addInt64(7, object.rpm);
        fbb.addInt64(8, object.smartBaselineGear);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final deviceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final startTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final durationSecsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final gearParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final wattsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final rpmParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final modeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final smartBaselineGearParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final object = UsageLog(
          id: idParam,
          deviceId: deviceIdParam,
          startTime: startTimeParam,
          durationSecs: durationSecsParam,
          gear: gearParam,
          watts: wattsParam,
          rpm: rpmParam,
          mode: modeParam,
          smartBaselineGear: smartBaselineGearParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FanDevice] entity fields to define ObjectBox queries.
class FanDevice_ {
  /// See [FanDevice.id].
  static final id = obx.QueryIntegerProperty<FanDevice>(
    _entities[0].properties[0],
  );

  /// See [FanDevice.deviceId].
  static final deviceId = obx.QueryStringProperty<FanDevice>(
    _entities[0].properties[1],
  );

  /// See [FanDevice.macAddress].
  static final macAddress = obx.QueryStringProperty<FanDevice>(
    _entities[0].properties[2],
  );

  /// See [FanDevice.model].
  static final model = obx.QueryStringProperty<FanDevice>(
    _entities[0].properties[3],
  );

  /// See [FanDevice.nickname].
  static final nickname = obx.QueryStringProperty<FanDevice>(
    _entities[0].properties[4],
  );

  /// See [FanDevice.fwVersion].
  static final fwVersion = obx.QueryStringProperty<FanDevice>(
    _entities[0].properties[5],
  );

  /// See [FanDevice.addedAt].
  static final addedAt = obx.QueryDateProperty<FanDevice>(
    _entities[0].properties[6],
  );

  /// See [FanDevice.lastConnectedAt].
  static final lastConnectedAt = obx.QueryDateProperty<FanDevice>(
    _entities[0].properties[7],
  );

  /// See [FanDevice.isServiceAccess].
  static final isServiceAccess = obx.QueryBooleanProperty<FanDevice>(
    _entities[0].properties[8],
  );

  /// See [FanDevice.serviceExpiresAt].
  static final serviceExpiresAt = obx.QueryDateProperty<FanDevice>(
    _entities[0].properties[9],
  );
}

/// [FanState] entity fields to define ObjectBox queries.
class FanState_ {
  /// See [FanState.id].
  static final id = obx.QueryIntegerProperty<FanState>(
    _entities[1].properties[0],
  );

  /// See [FanState.deviceId].
  static final deviceId = obx.QueryStringProperty<FanState>(
    _entities[1].properties[1],
  );

  /// See [FanState.speed].
  static final speed = obx.QueryIntegerProperty<FanState>(
    _entities[1].properties[2],
  );

  /// See [FanState.isBoost].
  static final isBoost = obx.QueryBooleanProperty<FanState>(
    _entities[1].properties[3],
  );

  /// See [FanState.activeMode].
  static final activeMode = obx.QueryStringProperty<FanState>(
    _entities[1].properties[4],
  );

  /// See [FanState.activeTimerCode].
  static final activeTimerCode = obx.QueryIntegerProperty<FanState>(
    _entities[1].properties[5],
  );

  /// See [FanState.isPowered].
  static final isPowered = obx.QueryBooleanProperty<FanState>(
    _entities[1].properties[6],
  );

  /// See [FanState.lastWatts].
  static final lastWatts = obx.QueryIntegerProperty<FanState>(
    _entities[1].properties[7],
  );

  /// See [FanState.lastRpm].
  static final lastRpm = obx.QueryIntegerProperty<FanState>(
    _entities[1].properties[8],
  );

  /// See [FanState.lastLightColorType].
  static final lastLightColorType = obx.QueryStringProperty<FanState>(
    _entities[1].properties[9],
  );

  /// See [FanState.lastLightBrightness].
  static final lastLightBrightness = obx.QueryDoubleProperty<FanState>(
    _entities[1].properties[10],
  );

  /// See [FanState.lastLightIsOn].
  static final lastLightIsOn = obx.QueryBooleanProperty<FanState>(
    _entities[1].properties[11],
  );

  /// See [FanState.openSegmentStart].
  static final openSegmentStart = obx.QueryDateProperty<FanState>(
    _entities[1].properties[12],
  );

  /// See [FanState.openSegmentGear].
  static final openSegmentGear = obx.QueryIntegerProperty<FanState>(
    _entities[1].properties[13],
  );

  /// See [FanState.openSegmentMode].
  static final openSegmentMode = obx.QueryStringProperty<FanState>(
    _entities[1].properties[14],
  );

  /// See [FanState.openSegmentSmartBaseline].
  static final openSegmentSmartBaseline = obx.QueryIntegerProperty<FanState>(
    _entities[1].properties[15],
  );

  /// See [FanState.openSegmentWattsSum].
  static final openSegmentWattsSum = obx.QueryIntegerProperty<FanState>(
    _entities[1].properties[16],
  );

  /// See [FanState.openSegmentWattsCount].
  static final openSegmentWattsCount = obx.QueryIntegerProperty<FanState>(
    _entities[1].properties[17],
  );

  /// See [FanState.openSegmentRpmSum].
  static final openSegmentRpmSum = obx.QueryIntegerProperty<FanState>(
    _entities[1].properties[18],
  );

  /// See [FanState.openSegmentRpmCount].
  static final openSegmentRpmCount = obx.QueryIntegerProperty<FanState>(
    _entities[1].properties[19],
  );

  /// See [FanState.lastRuntimeSecs].
  static final lastRuntimeSecs = obx.QueryIntegerProperty<FanState>(
    _entities[1].properties[20],
  );

  /// See [FanState.timerActivatedAt].
  static final timerActivatedAt = obx.QueryDateProperty<FanState>(
    _entities[1].properties[21],
  );
}

/// [UsageLog] entity fields to define ObjectBox queries.
class UsageLog_ {
  /// See [UsageLog.id].
  static final id = obx.QueryIntegerProperty<UsageLog>(
    _entities[2].properties[0],
  );

  /// See [UsageLog.deviceId].
  static final deviceId = obx.QueryStringProperty<UsageLog>(
    _entities[2].properties[1],
  );

  /// See [UsageLog.startTime].
  static final startTime = obx.QueryDateProperty<UsageLog>(
    _entities[2].properties[2],
  );

  /// See [UsageLog.durationSecs].
  static final durationSecs = obx.QueryIntegerProperty<UsageLog>(
    _entities[2].properties[3],
  );

  /// See [UsageLog.gear].
  static final gear = obx.QueryIntegerProperty<UsageLog>(
    _entities[2].properties[4],
  );

  /// See [UsageLog.watts].
  static final watts = obx.QueryIntegerProperty<UsageLog>(
    _entities[2].properties[5],
  );

  /// See [UsageLog.mode].
  static final mode = obx.QueryStringProperty<UsageLog>(
    _entities[2].properties[6],
  );

  /// See [UsageLog.rpm].
  static final rpm = obx.QueryIntegerProperty<UsageLog>(
    _entities[2].properties[7],
  );

  /// See [UsageLog.smartBaselineGear].
  static final smartBaselineGear = obx.QueryIntegerProperty<UsageLog>(
    _entities[2].properties[8],
  );
}
